(() => {
  "use strict";
  const B = "v4.0.1-root-fix";
  const G = { w: 1800, gate: 1690, gy: 430, grav: 1500, walk: 230, dash: 360, jump: -620, cost: 8 };
  const d = {}, S = { run:false, bossRun:false, last:0, blast:0, cam:0, p:null, bp:null, boss:null, e:[], r:[], q:[], h:null, inp:{left:false,right:false}, binp:{left:false,right:false}, lock:false, block:false };
  document.addEventListener("DOMContentLoaded", init);
  function init(){["safeHub","menu","hub","customize","gallery","game","boss","result","hubText","resultText","resultStats","levelCanvas","bossCanvas","armorDots","levelHealth","levelHealthFill","levelEnergy","levelMessage","levelLeft","levelRight","levelJump","levelAttack","levelDash","levelRestart","bossArmorDots","bossPlayerHealth","bossPlayerHealthFill","bossEnergy","bossHitsLeft","bossHealthFill","bossMessage","bossLeft","bossRight","bossJump","bossAttack","bossDash","bossRestart"].forEach(x=>d[x]=document.getElementById(x));d.l=d.levelCanvas.getContext("2d");d.b=d.bossCanvas.getContext("2d");document.querySelectorAll("[data-build-tag]").forEach(x=>x.textContent=B);wire();reset();show("menu");}
  function wire(){document.addEventListener("click",e=>{const g=e.target?.dataset?.go;if(g)show(g)});d.safeHub.onclick=()=>show("hub");d.levelRestart.onclick=reset;d.bossRestart.onclick=startBoss;hold(d.levelLeft,()=>lh("left",true),()=>lh("left",false));hold(d.levelRight,()=>lh("right",true),()=>lh("right",false));press(d.levelJump,()=>la("jump"));press(d.levelAttack,()=>la("atk"));press(d.levelDash,()=>la("dash"));hold(d.bossLeft,()=>S.binp.left=true,()=>S.binp.left=false);hold(d.bossRight,()=>S.binp.right=true,()=>S.binp.right=false);press(d.bossJump,()=>jump(S.bp));press(d.bossAttack,batk);press(d.bossDash,()=>dash(S.bp,msgb,hudb));document.addEventListener("touchmove",e=>e.preventDefault(),{passive:false});["contextmenu","selectstart","dragstart","gesturestart"].forEach(t=>document.addEventListener(t,e=>e.preventDefault()));}
  function press(b,f){let a=false;b.onpointerdown=e=>{e.preventDefault();if(a)return;a=true;f();b.blur()};const u=e=>{e.preventDefault();a=false;b.blur()};b.onpointerup=u;b.onpointercancel=u;b.onpointerleave=u}
  function hold(b,f,u){let a=false;b.onpointerdown=e=>{e.preventDefault();if(a)return;a=true;f();b.blur()};const r=e=>{e.preventDefault();if(!a)return;a=false;u();b.blur()};b.onpointerup=r;b.onpointercancel=r;b.onpointerleave=r}
  function show(x){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("is-active"));(d[x]||d.hub).classList.add("is-active");S.run=false;S.bossRun=false;S.inp.left=S.inp.right=S.binp.left=S.binp.right=false;if(x==="game")start();if(x==="boss")startBoss();scrollTo(0,0)}
  function P(o={}){return{x:70,y:360,w:34,h:66,vx:0,vy:0,face:1,on:false,armor:3,hp:100,en:0,atk:0,inv:0,dt:0,int:0,gr:0,gate:false,...o}}
  function reset(){S.h=null;S.cam=0;S.lock=false;S.p=P();S.e=[E("slime",500,396,38,34,1,{j:true}),E("goblin",930,382,50,48,2),E("bat",1240,250,46,34,2,{f:true})];S.r=[R(690,405),R(1120,405)];S.q=[{x:720,y:330,g:false},{x:1420,y:320,g:false}];msg("Root fix: fill the meter to release");hud();draw(0)}
  function start(){reset();S.run=true;S.last=performance.now();requestAnimationFrame(loop)}
  function E(k,x,y,w,h,hp,o={}){return{k,x,y,w,h,hp,m:hp,dir:-1,t:0,...o}}
  function R(x,y){return{x,y,w:92,h:25,u:false,a:false,t:0}}
  function msg(t){d.levelMessage.textContent=t}function msgb(t){d.bossMessage.textContent=t}
  function dots(n){return[1,2,3].map(i=>`<i class="dot ${i<=n?"":"is-empty"}"></i>`).join("")}
  function hud(){const p=S.p;d.armorDots.innerHTML=dots(p.armor);d.levelHealth.textContent=Math.ceil(Math.max(0,p.hp));d.levelHealthFill.style.width=`${clamp(p.hp,0,100)}%`;d.levelEnergy.textContent=Math.floor(p.en);d.levelDash.classList.toggle("is-locked",p.en<G.cost)}
  function hudb(){const p=S.bp,b=S.boss;d.bossArmorDots.innerHTML=dots(p.armor);d.bossPlayerHealth.textContent=Math.ceil(Math.max(0,p.hp));d.bossPlayerHealthFill.style.width=`${clamp(p.hp,0,100)}%`;d.bossEnergy.textContent=Math.floor(p.en);d.bossHitsLeft.textContent=Math.max(0,Math.ceil(b.hp/10));d.bossHealthFill.style.width=`${clamp(b.hp,0,100)}%`;d.bossDash.classList.toggle("is-locked",p.en<G.cost)}
  function lh(k,v){if(S.h&&v){tap();return}S.inp[k]=v}function la(a){if(S.h){tap();return}if(a==="jump")jump(S.p);if(a==="atk")atk();if(a==="dash")dash(S.p,msg,hud)}
  function jump(p){if(p&&p.on){p.vy=G.jump;p.on=false}}function dash(p,m,h){if(!p||p.en<G.cost)return;p.en-=G.cost;p.dt=.42;p.inv=.8;p.int=.95;p.vx=G.dash*p.face;m("Intangible");h()}
  function atk(){const p=S.p;if(S.lock)return;S.lock=true;setTimeout(()=>S.lock=false,120);p.atk=.14;p.en=Math.min(100,p.en+4);let b=abox(p,54),hit=null;S.e.forEach(e=>{if(e.hp>0&&over(b,e))hit=e});if(hit){hit.hp--;p.en=Math.min(100,p.en+16);msg(hit.hp<=0?"Enemy down":`${hit.k} HP ${hit.hp}/${hit.m}`)}else msg("Miss");hud()}
  function abox(a,r){return{x:a.face>0?a.x+a.w:a.x-r,y:a.y+10,w:r,h:38}}function can(p){return p.inv<=0&&p.dt<=0&&p.int<=0&&p.gr<=0&&!S.h}
  function actor(p,i,dt,max){p.atk=Math.max(0,p.atk-dt);p.inv=Math.max(0,p.inv-dt);p.dt=Math.max(0,p.dt-dt);p.int=Math.max(0,p.int-dt);p.gr=Math.max(0,p.gr-dt);let ax=+i.right-+i.left;if(ax){p.face=ax;p.vx=ax*(p.dt>0?G.dash:G.walk)}else if(p.dt<=0)p.vx*=.82;p.vy+=G.grav*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.y+p.h>=G.gy){p.y=G.gy-p.h;p.vy=0;p.on=true}else p.on=false;p.x=clamp(p.x,20,max)}
  function update(dt){let p=S.p;if(S.h){holdUpdate(dt);S.cam=clamp(p.x-330,0,G.w-960);return}actor(p,S.inp,dt,G.w-80);S.cam=clamp(p.x-330,0,G.w-960);S.r.forEach(r=>{r.t+=dt;if(!r.u&&over(p,r)&&can(p))beginHold(r)});S.e.forEach(e=>{if(e.hp<=0)return;moveE(e,dt);if(over(p,e)&&can(p))hurt(e.f)});S.q.forEach(q=>{if(!q.g&&dist(p.x+17,p.y+33,q.x,q.y)<42){q.g=true;p.en=Math.min(100,p.en+25);msg("Pickup");hud()}});if(p.x>G.gate&&!p.gate){p.gate=true;msg("Boss gate reached");setTimeout(()=>show("boss"),450)}}
  function moveE(e,dt){e.t+=dt;if(e.f){e.x+=e.dir*82*dt;e.y=245+Math.sin(e.t*3)*38;if(e.x<1150||e.x>1440)e.dir*=-1;return}if(e.j){e.x+=e.dir*58*dt;e.y=G.gy-e.h-Math.abs(Math.sin(e.t*4.8))*42;if(e.x<390||e.x>760)e.dir*=-1;return}e.x+=e.dir*65*dt;if(e.x<840||e.x>1080)e.dir*=-1;e.y=G.gy-e.h}
  function hurt(ign){let p=S.p;p.inv=1;p.en=Math.min(100,p.en+12);if(p.armor>0&&!ign){p.armor--;msg("Armor layer hit")}else{p.hp-=25;msg("Health damage")}hud();if(p.hp<=0)setTimeout(reset,700)}
  function beginHold(r){let p=S.p;r.a=true;p.vx=p.vy=p.dt=p.int=p.inv=0;p.x=clamp(r.x+r.w/2-p.w/2,20,G.w-80);p.y=G.gy-p.h;S.inp.left=S.inp.right=false;S.h={r,phase:"try",n:0,need:5,t:3};msg("Held! Tap Jump / Atk / Dash to release");hud()}
  function tap(){let h=S.h;if(!h||h.phase==="done")return;h.n++;msg(h.phase==="try"?`Releasing: ${h.n}/${h.need}`:`Final release: ${h.n}/${h.need}`);if(h.n>=h.need)release()}
  function holdUpdate(dt){let h=S.h,p=S.p;p.vx=p.vy=p.dt=p.int=p.inv=0;p.y=G.gy-p.h;if(h.phase==="try"){h.t-=dt;if(h.t<=0){if(p.armor>0){p.armor--;hud();msg(p.armor>0?"Layer lost — keep tapping":"Last layer lost — still releasable")}if(p.armor<=0){h.phase="late";h.n=0;h.need=9;msg("Late hold — keep tapping to release");return}h.t+=2}}else if(h.phase==="late"){p.hp=Math.max(0,p.hp-5*dt);hud();if(p.hp<=0){h.phase="done";msg("Down - Restart or Hub")}}}
  function release(){let h=S.h,p=S.p,r=h.r;r.u=true;r.a=false;S.h=null;p.gr=1.2;p.inv=1.2;p.x=clamp(r.x+r.w+36,20,G.w-80);p.y=G.gy-p.h;p.vx=0;p.en=Math.min(100,p.en+10);msg("Released — root disabled");hud()}
  function startBoss(){const s=S.p||P({en:20});S.bp=P({x:110,armor:s.armor,hp:s.hp,en:Math.max(20,s.en)});S.boss={x:670,y:326,w:120,h:104,hp:100,cd:.7,tele:0,wind:0,type:"orb",shots:[]};msgb(`Build ${B}`);hudb();drawBoss(0);S.bossRun=true;S.blast=performance.now();requestAnimationFrame(bloop)}
  function bupdate(dt){let p=S.bp,b=S.boss;actor(p,S.bossInput,dt,820);b.cd-=dt;b.wind=Math.max(0,b.wind-dt);if(b.tele>0){b.tele-=dt;if(b.tele<=0)bfire()}b.x+=Math.sign(mid(p)-mid(b))*36*dt;b.x=clamp(b.x,520,820);if(b.cd<=0&&b.tele<=0&&b.wind<=0){b.cd=1.05;let orb=Math.abs(mid(p)-mid(b))>215||b.type==="slam";b.type=orb?"orb":"slam";b.tele=orb?.38:.3;msgb(orb?"King Slime forms a glob":"King Slime swells up")}if(b.wind>0&&over(p,zone()))bhurt();b.shots.forEach(s=>{s.x+=s.vx*dt;s.life-=dt;if(over(p,s)&&p.inv<=0&&p.dt<=0&&p.int<=0){s.life=0;bhurt()}});b.shots=b.shots.filter(s=>s.life>0&&s.x>-80&&s.x<1040);if(over(p,b)&&p.inv<=0&&p.dt<=0&&p.int<=0)bhurt()}
  function bfire(){let p=S.bp,b=S.boss;if(b.type==="slam")b.wind=.22;else{let dir=mid(p)<mid(b)?-1:1;b.shots.push({x:b.x+b.w/2,y:b.y+50,w:28,h:28,vx:dir*290,life:2.8})}}
  function zone(){let b=S.boss;return{x:b.x-74,y:b.y+18,w:b.w+148,h:82}}function bhurt(){let p=S.bp;p.inv=1;p.en=Math.min(100,p.en+12);if(p.armor>0){p.armor--;msgb("Armor layer hit")}else{p.hp-=18;msgb("Health damage")}hudb();if(p.hp<=0)setTimeout(startBoss,700)}
  function batk(){let p=S.bp,b=S.boss;if(S.bossAtkLock||b.hp<=0)return;S.bossAtkLock=true;setTimeout(()=>S.bossAtkLock=false,150);p.atk=.14;p.en=Math.min(100,p.en+4);if(over(abox(p,62),b)){b.hp-=10;p.en=Math.min(100,p.en+14);msgb(b.hp>0?`King Slime: ${Math.ceil(b.hp/10)} hits left`:"King Slime defeated");hudb();if(b.hp<=0)finish()}else{msgb("Miss");hudb()}}
  function finish(){let p=S.bp;S.bossRun=false;d.resultText.textContent="King Slime defeated. Forest route cleared.";d.resultStats.textContent=`Remaining health: ${Math.ceil(Math.max(0,p.hp))} | Armor layers: ${p.armor} | Energy: ${Math.floor(p.en)}`;setTimeout(()=>show("result"),700)}
  function loop(t){if(!S.run)return;let dt=Math.min(.033,(t-S.last)/1000);S.last=t;update(dt);draw(t/1000);requestAnimationFrame(loop)}function bloop(t){if(!S.bossRun)return;let dt=Math.min(.033,(t-S.blast)/1000);S.blast=t;bupdate(dt);drawBoss(t/1000);requestAnimationFrame(bloop)}
  function clear(c){let g=c.createLinearGradient(0,0,0,430);g.addColorStop(0,C.bg1);g.addColorStop(1,C.bg2);c.fillStyle=g;c.fillRect(0,0,960,540)}
  function draw(t){let c=d.l,cam=S.cam;clear(c);forest(c,cam);ground(c,-cam,G.w);roots(c,cam,t);gate(c,cam,t);items(c,cam,t);ents(c,cam,t);fx(c,S.p,54,cam);witch(c,S.p,cam,t);wrap(c,S.p,cam,t);box(c,S.p,cam);overlay(c)}
  function drawBoss(t){let c=d.b,b=S.boss;clear(c);forest(c,0);ground(c,0,960);if(b.tele>0&&b.type==="slam")slam(c,zone(),t,false);if(b.wind>0)slam(c,zone(),t,true);b.shots.forEach(s=>shot(c,s,t));king(c,b,t);fx(c,S.bp,62,0);witch(c,S.bp,0,t);box(c,S.bp,0);c.fillStyle=C.white;c.font="16px system-ui";c.fillText(`King Slime hits left: ${Math.max(0,Math.ceil(b.hp/10))}`,20,34)}
  function forest(c,cam){tree(c,cam*.16,72,"#1e1b4b",.8);tree(c,cam*.32,132,"#312e81",.58);tree(c,cam*.52,196,"#111827",.74)}function tree(c,cam,y,col,a){c.save();c.globalAlpha=a;c.fillStyle=col;for(let x=-120;x<1100;x+=96){let dx=x-(cam%96),h=210+((x*7)%70);c.fillRect(dx+38,y+160-h,20,h);c.beginPath();c.moveTo(dx-12,y+160-h+65);c.lineTo(dx+48,y+160-h-30);c.lineTo(dx+110,y+160-h+65);c.closePath();c.fill()}c.restore()}function ground(c,ox,w){c.fillStyle=C.ground;c.fillRect(ox,G.gy,w,110);c.fillStyle=C.groundTop;c.fillRect(ox,G.gy,w,10)}
  function roots(c,cam,t){S.r.forEach(r=>{let x=r.x-cam;c.save();c.globalAlpha=r.u?.18:1;c.fillStyle=r.a?"rgba(244,114,182,.45)":"rgba(52,211,153,.28)";c.beginPath();c.ellipse(x+r.w/2,r.y+r.h/2,r.w/2,r.h/2+Math.sin(t*5+r.x)*2,0,0,Math.PI*2);c.fill();c.strokeStyle=r.u?"rgba(148,163,184,.5)":"rgba(209,250,229,.65)";c.lineWidth=3;for(let i=0;i<4;i++){c.beginPath();c.moveTo(x+12+i*20,r.y+18);c.quadraticCurveTo(x+8+i*24,r.y-12-Math.sin(t*6+i)*8,x+22+i*20,r.y+8);c.stroke()}c.restore()})}
  function gate(c,cam,t){let x=G.gate-cam;c.save();c.translate(x+24,378);c.fillStyle="rgba(192,132,252,.15)";c.beginPath();c.ellipse(0,4,48+Math.sin(t*4)*3,78,0,0,Math.PI*2);c.fill();c.fillStyle="#6b21a8";c.fillRect(-22,-50,44,100);c.fillStyle="#f9a8d4";c.fillRect(-13,-39,26,78);c.restore()}function items(c,cam,t){S.q.forEach(p=>{if(p.g)return;c.fillStyle=C.magic;c.beginPath();c.arc(p.x-cam,p.y+Math.sin(t*5)*4,13,0,Math.PI*2);c.fill()})}
  function ents(c,cam,t){S.e.forEach(e=>{if(e.hp<=0)return;if(e.k==="slime"){c.fillStyle=C.greenDark;c.beginPath();c.ellipse(e.x-cam+e.w/2,e.y+e.h-12,22,18,0,0,Math.PI*2);c.fill();c.fillStyle=C.green;c.beginPath();c.ellipse(e.x-cam+e.w/2,e.y+e.h-17,16,12,0,0,Math.PI*2);c.fill()}else if(e.k==="goblin"){c.fillStyle=C.goblin;c.fillRect(e.x-cam+8,e.y+18,34,30);c.beginPath();c.ellipse(e.x-cam+25,e.y+9,17,14,0,0,Math.PI*2);c.fill()}else{let x=e.x-cam+e.w/2,y=e.y+e.h/2,fl=Math.sin(t*15)*13;c.fillStyle="rgba(124,45,18,.6)";c.beginPath();c.moveTo(x-8,y);c.quadraticCurveTo(x-42,y-24-fl,x-38,y+20);c.lineTo(x-9,y+13);c.closePath();c.fill();c.beginPath();c.moveTo(x+8,y);c.quadraticCurveTo(x+42,y-24+fl,x+38,y+20);c.lineTo(x+9,y+13);c.closePath();c.fill();c.fillStyle=C.bat;c.beginPath();c.ellipse(x,y,15,12,0,0,Math.PI*2);c.fill()}c.fillStyle="#fff";c.font="12px system-ui";c.fillText(String(e.hp),e.x-cam+e.w/2-3,e.y-7)})}
  function fx(c,p,r,cam){if(!p||p.atk<=0)return;let b=abox(p,r);c.fillStyle="rgba(251,191,36,.65)";c.beginPath();c.ellipse(b.x-cam+r/2,b.y+18,r*.58,26,0,0,Math.PI*2);c.fill()}function witch(c,p,cam,t){if(!p)return;let x=p.x-cam+p.w/2,y=p.y+p.h;c.save();c.translate(x,y+(p.on?Math.sin(t*10)*Math.min(1,Math.abs(p.vx)/G.walk)*2:-2));c.scale(p.face,1);c.fillStyle=C.black;c.beginPath();c.moveTo(-18,-58);c.quadraticCurveTo(-31,-38,-24,-12);c.lineTo(18,-14);c.lineTo(16,-58);c.closePath();c.fill();if(p.armor>=2){c.fillStyle=C.pink;c.fillRect(-17,-54,24,34)}c.fillStyle=p.armor>0?C.outfit:"#d8b4fe";c.fillRect(-14,-61,28,36);c.fillStyle=C.skin;c.fillRect(-11,-31,8,20);c.fillRect(4,-31,8,20);c.fillStyle=C.black;c.fillRect(-13,-15,11,17);c.fillRect(3,-15,11,17);c.fillStyle=C.skin;c.beginPath();c.arc(0,-76,13,0,Math.PI*2);c.fill();c.fillStyle=C.pink;c.beginPath();c.ellipse(-2,-82,17,14,-.22,0,Math.PI*2);c.fill();c.fillStyle=C.black;c.beginPath();c.ellipse(0,-88,28,6,0,0,Math.PI*2);c.fill();c.beginPath();c.moveTo(-14,-89);c.quadraticCurveTo(-3,-126,14,-91);c.closePath();c.fill();c.restore()}function wrap(c,p,cam,t){let h=S.h;if(!h||!p||h.phase==="done")return;let x=p.x-cam+p.w/2,y=p.y+p.h;c.strokeStyle=h.phase==="try"?"rgba(52,211,153,.9)":"rgba(244,114,182,.9)";c.lineWidth=5;for(let i=0;i<5;i++){c.beginPath();c.moveTo(x-36+i*18,y+2);c.quadraticCurveTo(x-28+i*12,y-35-Math.sin(t*7+i)*8,x-18+i*9,y-18);c.stroke()}}
  function overlay(c){let h=S.h;if(!h)return;let late=h.phase==="late";c.fillStyle="rgba(15,23,42,.72)";c.fillRect(150,22,660,late?112:94);c.strokeStyle="rgba(255,255,255,.18)";c.strokeRect(150,22,660,late?112:94);c.fillStyle="#fff";c.font="18px system-ui";if(h.phase==="try"){c.fillText("HELD — tap Jump / Atk / Dash to release",175,52);bar(c,h.n,h.need,175,68);c.fillStyle="#cbd5e1";c.font="14px system-ui";c.fillText(`Release ${h.n}/${h.need}    Next layer: ${Math.max(0,h.t).toFixed(1)}s`,175,105)}else if(late){c.fillText("LATE HOLD — keep tapping to release",175,52);bar(c,h.n,h.need,175,68);c.fillStyle="#cbd5e1";c.font="14px system-ui";c.fillText(`Release ${h.n}/${h.need}    Health lowers slowly`,175,105)}else{c.fillText("DOWN",175,52);c.fillStyle="#cbd5e1";c.font="15px system-ui";c.fillText("Use Restart or Hub.",175,82)}}function bar(c,v,m,x,y){c.fillStyle="#374151";c.fillRect(x,y,420,18);c.fillStyle=C.green;c.fillRect(x,y,420*(v/m),18);c.strokeStyle="rgba(255,255,255,.28)";c.strokeRect(x,y,420,18)}
  function king(c,b,t){let wob=Math.sin(t*5)*6;c.save();c.translate(b.x+b.w/2,b.y+b.h);c.fillStyle=C.purple;c.beginPath();c.moveTo(-66,0);c.quadraticCurveTo(-70,-64+wob,-8,-92);c.quadraticCurveTo(54,-72-wob,66,0);c.quadraticCurveTo(22,15,-66,0);c.closePath();c.fill();c.fillStyle=C.white;c.fillRect(-24,-54,8,8);c.fillRect(18,-54,8,8);c.fillStyle=C.trim;c.beginPath();c.moveTo(-24,-82);c.lineTo(-10,-106);c.lineTo(2,-86);c.lineTo(18,-108);c.lineTo(28,-79);c.closePath();c.fill();c.restore()}function slam(c,z,t,a){c.fillStyle=a?"rgba(251,113,133,.32)":"rgba(251,113,133,.16)";c.fillRect(z.x,z.y,z.w,z.h)}function shot(c,s,t){c.fillStyle=C.green;c.beginPath();c.arc(s.x,s.y,12+Math.sin(t*12)*1.5,0,Math.PI*2);c.fill()}function box(c,p,cam){if(!p)return;c.strokeStyle="rgba(56,189,248,.18)";c.strokeRect(p.x-cam,p.y,p.w,p.h)}
  function over(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}function mid(r){return r.x+r.w/2}function dist(x1,y1,x2,y2){return Math.hypot(x1-x2,y1-y2)}function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
})();